### ISSUE TITLE
Encountered mounting errors when using rshared option

### ISSUE THREAD

**Issue by tiverive** [efrecon/docker-webdav-client#11]
Hi, so I've been trying to run the docker-webdav client in my homelab running Ubuntu 21.04 with Docker (Docker version 19.03.13, build cd8016b6bc) running in a snap process. I'm getting the following error when I start the app. Any ideas what the issue could be?
    
    ERROR: for wilson_webdav  Cannot start service wilson_webdav: path /home/perdomwx/web-stack/data/wilson_webdav is mounted on /home but it is not a shared mount
    ERROR: Encountered errors while bringing up the project.
    
Here's the docker-compose config I've been using.

     wilson_webdav:
        image: efrecon/webdav-client
        devices:
          - /dev/fuse
        cap_add:
          - SYS_ADMIN
        security_opt:
          - apparmor:unconfined
        environment:
          WEBDRIVE_USERNAME: email@example.com
          WEBDRIVE_PASSWORD: example
          WEBDRIVE_URL: seafile/seafdav
          DAVFS2_ASK_AUTH: 0
        volumes:
          - $PWD/data/wilson_webdav:/mnt/webdrive:rshared
          
I've seen that the following command could help resolve the issue but it doesn't make any difference. 

  sudo mount --make-shared /home

Any help is appreciated.

**Comment by efrecon** [comment]
I am sorry, but I do not really know. Could it be that you are running via `snap` and that `snap` prevents some of the necessary mounting mechanisms? Can you verify through running against the same WebDAV server, but using either an older Ubuntu (e.g. 20.04 LTS) or using Docker installed directly from the official [repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) (i.e. not the Ubuntu default), in a virtual machine for example?

**Comment by tiverive** [comment]
Sorry for the late response. Just got a chance to test out your suggestion. It seems that the snap version of docker was causing the issue. It works with the version installed through apt. Thank you!
