### ISSUE TITLE
empty password webdav

### ISSUE THREAD

**Issue by Lengso** [efrecon/docker-webdav-client#18]
Some webdavs do not require a password but can still write, causing
/etc/davfs2/secrets:69: malformed line
```
if [ -n "${WEBDRIVE_USERNAME}" ] && [ -n "${WEBDRIVE_PASSWORD}" ]; then
    echo "$DEST $WEBDRIVE_USERNAME $WEBDRIVE_PASSWORD" >> /etc/davfs2/secrets
    unset WEBDRIVE_PASSWORD
fi
```

**Comment by geimist** [comment]
I encounter the same error (in conjunction with local [Cryptomator](https://github.com/vh13294/cryptomator-docker)).
How can I work around this?

EDIT:
I was able to solve the problem as follows:
davfs2 apparently always expects a user name and password to be specified. In the case of a WebDAV server without credentials, you can simply enter dashes. I have adapted the file `docker-entrypoint.sh` as follows:

``` 
if [ -z "${WEBDRIVE_USERNAME}" ]; then
    echo "No username specified, is this on purpose?"
    # set up user name for anonymous access:
    WEBDRIVE_USERNAME="-"
fi
...
if [ -z "${WEBDRIVE_PASSWORD}" ]; then
    echo "No password specified, is this on purpose?"
    # set up password for anonymous access:
    WEBDRIVE_PASSWORD="-"
fi
```
