### ISSUE TITLE
Passing the server certificate

### ISSUE THREAD

**Issue by Glideh** [efrecon/docker-webdav-client#19]
Is there a way to pass the expected certificate for the server ?
> Server certificate verification failed: issuer is not trusted

**Comment by efrecon** [comment]
Yes. Mount a file with the certificate, and point to the location of that file within the container with the `DAVFS2_TRUST_SERVER_CERT` environment variable. See [here](https://github.com/efrecon/docker-webdav-client#davfs-options)
